name: Check R packages

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - 'LICENSE.txt'
      - '.github/**'
      - 'examples/**'
      - 'figs/**'
      - '*.Rcheck/**'
      - '.DS_Store'
      - 'bspcov_*.tar.gz'
      - 'CHANGELOG.md'
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - 'LICENSE.txt'
      - '.github/**'
      - 'examples/**'
      - 'figs/**'
      - '*.Rcheck/**'
      - '.DS_Store'
      - 'bspcov_*.tar.gz'
      - 'CHANGELOG.md'

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'release'}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install R Package Build Dependencies on MacOS
        if: ${{ runner.os == 'macOS' }}
        uses: r-hub/actions/setup-r-sysreqs@v1
        with:
          type: 'minimal'
      
      - uses: r-lib/actions/setup-renv@v2
      
      - uses: r-lib/actions/setup-tinytex@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
          
      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"error"'
          check-dir: '"check"'