name: Check R packages (dev)

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  pull_request:
    branches:
      - 'dev-**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE.txt'
      - '.github/**'
      - 'examples/**'
      - 'figs/**'
      - '*.Rcheck/**'
      - '.DS_Store'
      - 'bspcov_*.tar.gz'
      - 'CHANGELOG.md'
  push:
    branches:
      - 'dev-**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE.txt'
      - '.github/**'
      - 'examples/**'
      - 'figs/**'
      - '*.Rcheck/**'
      - '.DS_Store'
      - 'bspcov_*.tar.gz'
      - 'CHANGELOG.md'

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for git log commands

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install R Package Build Dependencies on MacOS
        if: ${{ runner.os == 'macOS' }}
        uses: r-hub/actions/setup-r-sysreqs@v1
        with:
          type: 'minimal'
      
      - uses: r-lib/actions/setup-renv@v2
      
      - uses: r-lib/actions/setup-tinytex@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"error"'
          check-dir: '"check"'
      
      # - name: get version
      #   # since this is dev-branch, use the version as the date + 000
      #   run: |
      #     export VERSION=$(date +'%Y.%m.%d').000
      #     echo "VERSION=${VERSION}" >> $GITHUB_ENV
      #     echo $VERSION

      # - name: update DESCRIPTION (version and date)
      #   run: |
      #   if [ "$RUNNER_OS" == "Linux" ]; then
      #         sed -i "s/Version: [^\"]*/Version: ${VERSION}/g" "DESCRIPTION"
      #         sed -i "s/Date: [^\"]*/Date: `date +'%Y-%m-%d'`/g" "DESCRIPTION"
      #    elif [ "$RUNNER_OS" == "Windows" ]; then
      #         choco install important_windows_software
      #    elif [ "$RUNNER_OS" == "macOS" ]; then
      #         sed -i "" "s/Version: [^\"]*/Version: ${VERSION}/g" "DESCRIPTION"
      #         sed -i "" "s/Date: [^\"]*/Date: `date +'%Y-%m-%d'`/g" "DESCRIPTION"
      #    else
      #         echo "$RUNNER_OS not supported"
      #         exit 1
      #    fi
      
      # - name: build package and manual
      #   run: |
      #     R CMD Rd2pdf --force --no-preview -o bspcov-manual.pdf .
      #     R CMD build .
