name: Deploy R packages (dev)

on:
  push:
    branches:
      - 'dev-**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE.txt'

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - name: Install R Package Build Dependencies on MacOS, from https://github.com/tdhock/atime/commit/d3d6220f08c9daa617e880b7cd57c958576f0ff4#diff-9c940e8ad2b7bc4c26ec3da57b94bc00e73e2166cfed689da51a4c59bcc0a310
        if: ${{ runner.os == 'macOS' }}
        uses: r-hub/actions/setup-r-sysreqs@v1
        with:
          type: 'minimal'

      - uses: r-lib/actions/setup-renv@v2
      
      - uses: r-lib/actions/setup-tinytex@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"error"'
          check-dir: '"check"'
      
      - name: get version
        # since this is dev-branch, use the version as the date + 000
        run: |
          export VERSION=$(date +'%Y.%m.%d').000
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo $VERSION

      - name: generate changelog
        run: |
          echo "## Changes since main branch" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          git log --format="### %s%n%n%b%n" main..HEAD >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "## Commit History" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          git log --oneline main..HEAD | sed 's/^/- /' >> CHANGELOG.md
          cat CHANGELOG.md

      - name: update DESCRIPTION (version and date)
        run: |
          sed -i "s/Version: [^\"]*/Version: ${VERSION}/g" "DESCRIPTION"
          sed -i "s/Date: [^\"]*/Date: `date +'%Y-%m-%d'`/g" "DESCRIPTION"
          sed -i "s/Packaged: [^\"]*/Packaged: `date +'%Y-%m-%d %H:%M:%S'` UTC; Kyeongwon Lee/g" "DESCRIPTION"
      
      - name: build package and manual
        run: |
          R CMD build .
          tar zxvf bspcov_$VERSION.tar.gz   
          R CMD Rd2pdf --force --no-preview --output=bspcov-manual.pdf bspcov
      
      - name: create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Delete existing dev-latest release if it exists
          gh release delete dev-latest --yes || true
          
          # Create new release with changelog
          gh release create dev-latest \
            --title "Development Build" \
            --notes-file CHANGELOG.md \
            --prerelease \
            bspcov-manual.pdf \
            bspcov_*.tar.gz